name: build-and-test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  schedule:
    # At 23:25 on Thursday.
    - cron: "25 23 * * 4"

jobs:
  default:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.x' ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install requirements
      run: python -m pip install -r requirements.txt
    - name: Build
      run: python -m pip install .
    - name: Test
      run: |
        cd examples
        python simple.py
